services:

web:
  build: .
  command: python /code/educa/manage.py runserver 0.0.0.0:8000
  restart: always
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  environment:
    - DJANGO_SETTING_MODULE=educa.settings.prod